server:
  port: 8082

spring:
  application:
    name: business-service
  profiles:
    active: basic
  cache:
    type: none


data-service:
  url: http://localhost:8081

# Настройки логирования
logging:
  level:
    by.step: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/business-service.log
    max-size: 10MB
    max-history: 30

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
        logger-level: full